<?php

namespace Container94ixKu6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5Kw_CHeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5Kw.CHe' shared service.
     *
     * @return \App\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BlogController::newAction()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?');
    }
}
