<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKMDo1J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKMDo1J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKMDo1J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKMDo1J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKMDo1J\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKMDo1J',
    'container.build_id' => 'dff0f45c',
    'container.build_time' => 1609682109,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKMDo1J');
